### ISSUE TITLE
Nested Route Specificity

### ISSUE THREAD

**Issue by tjni** [tildeio/route-recognizer#102]
I did some debugging on an issue I ran into in the Ember app I work on (v2.6.0) after updating the route-recognizer past 0.1.5, in which the specificity of some routes changed. It appears that the specificity of an array of nested routes is only given by the last one.

Here's a test case that passes before and fails after 0499446f80c649a2df64ced5cc5458742a57c42:

```
test("Matches the route with the longer static prefix.", function() {
  var handler1 = { handler: 1 };
  var handler2 = { handler: 2 };
  var router = new RouteRecognizer();

  router.add([{ path: "/:dynamic", handler: handler1 }, { path: "/", handler: handler1 }]);
  router.add([{ path: "/static", handler: handler2 }, { path: "/", handler: handler2 }]);

  resultsMatch(router.recognize("/static"), [
    { handler: handler2, params: { }, isDynamic: false },
    { handler: handler2, params: { }, isDynamic: false }
  ]);
});
```

Is this an expected change, a regression, or something that was never specified? Would love to hear folks' thoughts.

**Comment by jmeas** [comment]
@tjni seems unexpected to me. Got time to open a PR with this test case added?

**Comment by tjni** [comment]
Great timing :)

I was just about to submit a PR with a possible fix. Coincidentally, this is also something that #95 fixes as well in addition to everything else it's doing, so that will have merge conflicts with this.

**Comment by jmeas** [comment]
@tjni is this fixed by #101 being merged?

**Comment by rwjblue** [comment]
I believe that #101 was primarily fixing issues with the caching of valid chars that should have affected only wildcards. I wouldn't expect it to fix this also, but it's good to test/confirm.

**Comment by jmeas** [comment]
Ah, woops, my mistake. It's early, and I thought it was mentioned before that #101 was a fix for this when it is not. Sorry 😴

**Comment by mixonic** [comment]
@tjni you are on the right track here. Specificity of a previously added route was being stomped by a second route, and using an object as a bucket avoids the stomping. However I'm not sure this restores all the functionality we need (there are definitely two tests I have added that do not pass with it) however this is a step in the right direction.
