### ISSUE TITLE
.map missing in 0.2.5

### ISSUE THREAD

**Issue by hell03610** [tildeio/route-recognizer#113]
After installing `ember-cli-prenteder` on its latests version that fetches route-recognizer 0.2.5, the project won't compile saying route-recognizer.js.map was missing, as it is used [here](https://github.com/rwjblue/ember-cli-pretender/blob/master/index.js#L31).

```
└─┬ ember-cli-pretender@0.7.0
  └─┬ pretender@1.2.0
    └── route-recognizer@0.2.5
```

js.map was removed on this commit: https://github.com/tildeio/route-recognizer/commit/c57cc32e9bfef1f068538cf140e73bdf355e5cb9

**Comment by krisselden** [comment]
Switched to broccoli-rollup working on a separate issue but it's not outputting the map.  I could put an empty file there for now

**Comment by krisselden** [comment]
I released 0.2.6 would should provides a dummy map file so the build will work.

**Comment by krisselden** [comment]
Please let me know if this is fixed by 0.2.6

**Comment by rwjblue** [comment]
![screenshot](https://monosnap.com/file/okrFuqVwfWgaas4ASeOcsBWwe3dMAN.png)

Tested against 0.2.6, and seems to be working. Closing...

**Comment by hell03610** [comment]
Thx!
