### ISSUE TITLE
Unable to distinguish routes based on different methods/verbs

### ISSUE THREAD

**Issue by ronaldwidha** [tildeio/route-recognizer#115]
Since the API only requires path and handler to register a route, there isn't seem to be a way to match a route for a specific verb E.g. get and post might share the same uri structure but a totally different handler. 

The work around then is either to have a collection of handlers stored in each route, which can be enumerated after retrieval - which isn't ideal. or to have multiple routers.

**Comment by nathanhammond** [comment]
route-recognizer is a micro-library intended for parsing a URL and returning handlers. It has no knowledge of the network layer, what protocols it's using, and more.

I don't intend to add knowledge of HTTP verbs as I feel they should be handled by a layer above route-recognizer such as pretender.

Note that I also recommend that the handler itself be a string key which can be used to look up the handler on another object. This would allow you to compose additional information either into your lookup or have the handler be wrapped in a function which is verb aware.

I'm closing this as it isn't something we wish to change. Let us know what you come up with!
