### ISSUE TITLE
Clobbering inside of `names` object.

### ISSUE THREAD

**Issue by nathanhammond** [tildeio/route-recognizer#117]
```javascript
router.add([{ path: "/posts/:id/foo", handler: "post" }], { as: "post" });
router.add([{ path: "/posts/:id", handler: "post" }], { as: "post" });
```

This puts two routes into the NFA and one route into the `names` object by virtue of clobbering. Lookup by name will thus return the second route. However, `router.recognize('/posts/12/foo')` will still actually match and return the handler specified for the first route as it still exists in the NFA.

We should stop allowing you to clobber keys in the `names` object.

@wycats @rwjblue @krisselden @mixonic Confirm that this should be considered a bug?

/cc @trentmwillis

**Comment by mixonic** [comment]
This seems reasonable to me. @wycats?

**Comment by rwjblue** [comment]
Seems like a bug that we should fix to me...
