### ISSUE TITLE
Several routes consuming epsilon segments are now disallowed

### ISSUE THREAD

**Issue by cibernox** [tildeio/route-recognizer#121]
I found this problem after upgrading to Ember 2.10, but it's probably related with the changes in RR.

Assume the following routes:

```js
Router.map(function() {
  this.route('authenticated', { path: '/' }, function() {
    this.route('foo');
    this.route('bar');
  });
  this.route('landing-page', { path: '' });
});
```

In 2.9, visiting `/` rendered the `landing-page` route. In 2.10, an error about defining the application route twice is displayed.

Twidded demostrating the issue: https://ember-twiddle.com/630dfff296ebe1ffdb18eff18b1a9894?openFiles=router.js%2C

Toggle ember's version between 2.9 and 2.10 to see app work/fail.

**Comment by cibernox** [comment]
cc @nathanhammond

**Comment by medokin** [comment]
Seems like it works again since 2.11.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.
