### ISSUE TITLE
Building route-recognizer for non-Ember projects

### ISSUE THREAD

**Issue by yankrasny** [tildeio/route-recognizer#127]
Hi, I'm working on a non-Ember project (React/Redux, built with Webpack) and tried importing route-recognizer with no success. Is this library meant for use in non-Ember projects?

Here's what I did:
I ran `npm install route-recognizer` which gave me version 0.3.0. I then tried to `import RouteRecognizer from 'route-recognizer';` and the module wasn't found. The package.json file contains the following: `"main": "dist/route-recognizer.js"` and it looks like that file doesn't exist. The `dist` folder contains `route-recognizer, route-recognizer.d.ts, route-recognizer.es.js, and route-recognizer.es.js.map.`

**Comment by nathanhammond** [comment]
This is a recently-introduced issue. It should work with non-Ember projects just fine. Not high on my priority list, but if you open a PR to address it we'd accept it.

**Comment by nathanhammond** [comment]
Also, may be addressed on `master`.

**Comment by yankrasny** [comment]
Thanks for the quick reply! I happened to find a suitable replacement for my use case: https://github.com/rcs/route-parser

**Comment by krisselden** [comment]
when I do `npm pack` it is uncluded in the tar file, it maybe something I fixed after it was last published.

**Comment by krisselden** [comment]
fixed this
