### ISSUE TITLE
npm install defaults to version 0.2.9

### ISSUE THREAD

**Issue by rmehlinger** [tildeio/route-recognizer#131]
When I run `npm install --save route-recognizer`, by default version 0.2.9 is installed, despite 0.3.1 being the most recent version and Ember being dependent on ^0.3.0. https://www.npmjs.com/package/route-recognizer lists the most recent release as 0.2.9. It seems like whoever owns the npm repository needs to run npm publish?

**Comment by rwjblue** [comment]
Sorry about that! Fixed now...
