### ISSUE TITLE
update / clarify the claim about the <2kB library size in README.md

### ISSUE THREAD

**Issue by vlukashov** [tildeio/route-recognizer#141]
The very first paragraph of the README.md claims that the size of the route-recognizer library is under 2k:

> route-recognizer is a lightweight JavaScript library (under 2k!) that can be used as the recognizer for a more comprehensive router system (such as router.js).

As of `0.3.4` if I create an empty `index.js` file that only imports the 'route-recognizer' library, the size of output bundle is 13.3kB (minified), and 3.9kB (minified and gzipped). Am I missing something or is the README.me out of date? It looks like README should be saying "**(under 4kB gzipped!)**".

Steps to reproduce:
 - create a new npm / yarn project:
    `mkdir size-control && cd size-control && yarn init`
 - add route-recognizer, rollup and uglify-js as dependencies:
    `yarn add route-recognizer rollup uglify-js`
 - create a main.js file with a single import of 'route-recognizer':
    `echo "import RouteRecognizer from './node_modules/route-recognizer/dist/route-recognizer.es.js';" > index.js`
 - run rollup to bundle the module into a single file:
    `./node_modules/.bin/rollup index.js -o dist/bundle.js`
 - run uglifyjs to minify the bundle:
    `./node_modules/.bin/uglifyjs dist/bundle.js -o dist/bundle.min.js`
 - gzip the minified file (OS-dependent):
    `gzip dist/bundle.min.js --best -c > dist/bundle.min.js.gz`
 - check the size of the bundle: `ls -ls dist`

```
-rw-r--r--  1 viktor  staff  22752 Jan 22 11:30 bundle.js
-rw-r--r--  1 viktor  staff  13222 Jan 22 11:31 bundle.min.js
-rw-r--r--  1 viktor  staff   3916 Jan 22 11:32 bundle.min.js.gz
```

**Comment by rwjblue** [comment]
Sorry about that! The README is almost certainly incorrect and out of date.  Would love a PR to remove the actual sizing info from the README if you have the time...

We haven't done much to dig into making it smaller recently, but it sounds like we need to put this lib on a diet...
