### ISSUE TITLE
How to add a special regexp for param?

### ISSUE THREAD

**Issue by fundon** [tildeio/route-recognizer#38]
I knew, the param will default to `"([^/]+)"`.
How to change this and add special regexp for it.

**Comment by rafalp** [comment]
+1 this would greatly ease life for all of us non-rails guys having non-railsy routes to support in Ember.js

**Comment by jmeas** [comment]
UI-Router is a router to draw inspiration from here. It supports supplying a regex to override the default regex, as in

`'/user/{id:[0-9a-fA-F]{1,8}}'`,

which would only match hex values.

UI-Router also provides named aliases for common regexes, like `date`.

##### Pros

- Removes validation code out of the route itself

##### Cons

- Could potentially increase complexity of the specificity matching algorithm

I'm working on a router inspired by Ember's router, and I'm thinking I'll include this feature. If you're interested in supporting it @machty / @wycats, lmk. I'd be happy to try to put together a PR.

**Comment by jmeas** [comment]
I'm developing a DSL that supports this feature using an `=` as the operator.

`books/:bookId=\d{1,4}`

This wasn't my first choice for syntax – parentheses were – but most folks seem to prefer parentheses for optional segments. This feature doesn't affect capture groups, 'cause the general rule of thumb is to not use capture groups within the DSL as it messes with the generated regex.

I then thought to use `[]` or `{}`, but both of these conflict with RegExp features in ways I couldn't resolve. So I went with an equals sign.

Route recognizer doesn't support optional segments at the moment, so there's technically no conflict with using parentheses for this feature. But [it should](https://github.com/tildeio/route-recognizer/issues/60) support optional parts, and it should use parentheses for it, I think.

**Comment by fundon** [comment]
Nice work!

**Comment by nathanhammond** [comment]
Closing this in favor of https://github.com/emberjs/rfcs/pull/154.
