### ISSUE TITLE
No source map is available. Ember-cli asks for it

### ISSUE THREAD

**Issue by gagoman** [tildeio/route-recognizer#44]
Something like:

    Warning: ignoring input sourcemap for bower_components/route-recognizer/dist/route-recognizer.js
    because ENOENT

**Comment by seawatts** [comment]
+1 Having the same issue.

**Comment by cjroebuck** [comment]
+1 same for me since upgrading to ember-cli 0.1.12

**Comment by Robdel12** [comment]
Same issue here with ember cli pretender. 
`Warning: ignoring input sourcemap for bower_components/route-recognizer/dist/route-recognizer.js because ENOENT, no such file or directory '/Users/.../.../.../blog/ember/tmp/tree_merger-tmp_dest_dir-Ow3MPxou.tmp/bower_components/route-recognizer/dist/route-recognizer.js.map'`

**Comment by AlexSYanai** [comment]
Same Here:

`Warning: ignoring input sourcemap for bower_components/route-recognizer/dist/route-recognizer.js because ENOENT, no such file or directory '/home/../../../ember/tmp/tree_merger-tmp_dest_dir-nNouO1of.tmp/bower_components/route-recognizer/dist/route-recognizer.js.map'`

**Comment by backspace** [comment]
I think it’s safe to say many people are having this problem and further “same”-type comments are unnecessary. Hopefully we’ll hear back soon!

**Comment by amedr** [comment]
+1

**Comment by omarismail** [comment]
+1

**Comment by trek** [comment]
Locking because this is an identified issue and :+1:ing it just spams every collaborator

**Comment by machty** [comment]
Should be fixed.

**Comment by machty** [comment]
Actually it's not, but will be in a moment

**Comment by machty** [comment]
OK fixed in 0.1.9.
