### ISSUE TITLE
Use non-matching params as query params?

### ISSUE THREAD

**Issue by SamVerschueren** [tildeio/route-recognizer#51]
Hi

I am looking into the following issue of the new angular router (https://github.com/angular/router/issues/176). As I found out, if you want to add query parameters to generate an url, you'll have to add the queryParams property to the params object right?

Isn't it a better approach to take the non-matching segment parameters and use them as query params?

## Example
This is how it should be done right now with ```/user/:id``` as path.
```
router.generate('user', {id: 1234, queryParams: {hello: 'world'}});
    // -> /user/1234?hello=world
```

How it can be done
```
router.generate('user', {id: 1234, hello: 'world'});
    // -> /user/1234?hello=world
```

Because ```hello``` is not matching a parameter, it will be used as query string parameter.

**Comment by trek** [comment]
An interesting idea. If you'd like to fully flesh it out, check the guidelines on the https://github.com/emberjs/rfcs

**Comment by jmeas** [comment]
I dislike the "treat non-matching values are query params" pattern. I'd much rather be explicit about what I expect as a query param than rely on a 'fallback' algorithm.

**Comment by nathanhammond** [comment]
For reasons of stability for this library (this would be a backwards-incompatible change) and for performance of URL generation (which is a hot path that would start having to do bookkeeping) we're not going to make the change proposed here. Thank you for the idea, @SamVerschueren!
