### ISSUE TITLE
Publish version

### ISSUE THREAD

**Issue by knownasilya** [tildeio/route-recognizer#54]
Probably worth while releasing the new version with latest changes.

**Comment by knownasilya** [comment]
Ping?

**Comment by theazureshadow** [comment]
+1. The latest change looks like it'll address https://github.com/tildeio/route-recognizer/issues/44.

**Comment by quaertym** [comment]
:+1:

**Comment by machty** [comment]
Done, sorry for the delay.

**Comment by knownasilya** [comment]
Woo! :fireworks:
