### ISSUE TITLE
Optional dynamic segments

### ISSUE THREAD

**Issue by jmeas** [tildeio/route-recognizer#60]
In https://github.com/tildeio/router.js/issues/102, @mgenev expressed his frustration for dealing with a complex routing situation that he believed optional dynamic segments would resolve. @machty [said he would support this](https://github.com/tildeio/router.js/issues/102#issuecomment-41410325) were a PR made here in route-recognizer, so I'm creating this issue to document it as a todo.

Prior art:

##### Backbone

Optional segments are wrapped in parentheses. i.e. `docs/:section(/:subsection)`

##### React Router

A question mark marks the previous segment as optional. i.e. `docs/:section?`

However, React is apparently switching over to parentheses because of how annoying it is to deal with the question marks (ref: https://github.com/rackt/react-router/issues/960 )

**Comment by rizkytahara** [comment]
@jmeas any solution for this?

**Comment by jmeas** [comment]
I don't use Ember myself - I just stalk it - so I'm not sure if there's a preferred solution. My guess is you'll have to handle this logic in the route handler itself. If it doesn't pass your validation, then you could redirect it to another URL.

This is such an useful feature for any big app with lots of routes -- it's kinda crazy to me that both Ember's router and React Router both don't support it 😛

**Comment by jmeas** [comment]
Not that I'm aware of 😛

**Comment by nathanhammond** [comment]
Closing this in favor of https://github.com/emberjs/rfcs/pull/154.
