### ISSUE TITLE
Error behavior?

### ISSUE THREAD

**Issue by jmeas** [tildeio/route-recognizer#63]
For my own edification, I'm curious as to why `match(x).to(y, function() {});` [throws an error](https://github.com/tildeio/route-recognizer/blob/efc828d426f2ae9b21c0c27ebf61f4a150a6a67f/lib/route-recognizer/dsl.js#L18), but [not `match(x, function() {});`](https://github.com/tildeio/route-recognizer/blob/efc828d426f2ae9b21c0c27ebf61f4a150a6a67f/lib/route-recognizer/dsl.js#L55)? [It was added here](https://github.com/tildeio/route-recognizer/commit/d47e5c3c164058124c860908b586d0e20075235d), but without much explanation.

**Comment by nathanhammond** [comment]
That is something that should be considered a bug. Addressed in the reworking of this library and closing here.
