### ISSUE TITLE
Updated documentation – any interest?

### ISSUE THREAD

**Issue by jmeas** [tildeio/route-recognizer#64]
Is there any interest in an update to the docs? I've been going through Route Recognizer to figure out how it works, and I've taken a lot of notes that are neither in the README nor in code comments.

Perhaps the biggest omission from any documentation is the API exposed by [the DSL file](https://github.com/tildeio/route-recognizer/blob/master/lib/route-recognizer/dsl.js), which provides `Router#map`.

**Comment by nathanhammond** [comment]
Updated documentation will come as part of the rewrite, and a conceptual model of this library is [presented as a blog post](http://nathanhammond.com/route-recognizer).
