### ISSUE TITLE
Need a "builds" page

### ISSUE THREAD

**Issue by jamesarosen** [tildeio/route-recognizer#8]
[router.js](https://github.com/tildeio/router.js) and [rsvp.js](https://github.com/tildeio/rsvp.js) have pages on S3 that contain recent builds. JSFiddle no longer supports fetching source directly from GitHub (saying, "GitHub isn't a CDN") and this project doesn't have published versions, so it's hard to make a fiddle to show bugs in router.js.

**Comment by jmeas** [comment]
:clock1130: 2 years later

**Comment by nathanhammond** [comment]
At three years later with only this singular request this is not a priority distribution method for this library. Future changes will see it installable as an Ember Addon and packaged as a node module. Closing.
