### ISSUE TITLE
defining routes bulk and separately

### ISSUE THREAD

**Issue by arthur-s** [tildeio/route-recognizer#81]
Good day, when I add routes like this, urls not matching:
```javascript
        router.add([
		{ path: "/:lang/wall/posts/:slug", handler: articleController },
		{ path: "/:lang/wall/", handler: wallController },
		{ path: "/:lang/wall/category/:slug/", handler: wallController },
	]);
```

And all fine, when i add them separately:
```javascript
	router.add([{ path: "/ru/wall/", handler: wallController }]);
	router.add([{ path: "/:lang/wall/category/video", handler: wallController }]);
	router.add([{ path: "/:lang/wall/posts/:slug", handler: articleController }]);
```

tested urls:
/ru/wall/category/video
/ru/wall/
/ru/wall/posts/na-grebne-volny

**Comment by jmeas** [comment]
@arthur-s , you got bit by unexpected API of route-recognizer (I did too when I was first trying to figure it out!).

When you use a single `add` call, it builds up a single URL.

In other words, `router.add([a, b, c])` generates three routes:

`a`, `a/b`, and `a/b/c`.

In your first code sample, these are the routes you've created:

> `/:lang/wall/posts/:slug`
> `/:lang/wall/posts/:slug//:lang/wall/`
> `/:lang/wall/posts/:slug//:lang/wall//:lang/wall/category/:slug/`

which is probably not what you wanted :)

I'm not a huge fan of the route-recognizer API myself, but it iz wut it iz.

**Comment by arthur-s** [comment]
@jmeas , ahah) thanks for explanation! I begin to love more this little lib

**Comment by jmeas** [comment]
Np! ✌️

**Comment by rwjblue** [comment]
Thanks for answering @jmeas!
