### ISSUE TITLE
Suggestion: removing epsilon segments

### ISSUE THREAD

**Issue by jmeas** [tildeio/route-recognizer#85]
As I understand it, epsilon segments were added to support  index routes in a library like Router.js. While they do allow us to create that feature, they also bring some issues.

For instance, consider 3 epsilon segments in a row. Is that something worth supporting? I think allowing for epsilon segments means that we must, yet I'm not sure of the utility.

At the moment, epsilon segments are the last thing keeping route-recognizer from having a matching algorithm based solely on specificity and not order added. If you set up a test with 3 epsilon segments, and then a second route with 1 epsilon route, the order that you add them in determines which is matched.

It's probably not impossible to fix this, but is it worth it? If they're only around for index states, then there are more efficient ways to go about adding those in, without any side effects. If multiple epsilon segments is something that Ember wants to support, then there's more work to be done!

I can PR a fix for the sorting issue of epsilon segments, but I think a better idea would be to remove them if they're only around to allow for index states.

**Comment by jmeas** [comment]
Here's an example test that shows an issue with epsilon segments:

```js
test("Handle double empty segments before single empty segments.", function() {
  var handler1 = { handler: 1 };
  var handler2 = { handler: 2 };
  var handler3 = { handler: 3 };
  var router = new RouteRecognizer();

  router.add([{ path: "/", handler: handler1 }, { path: "/", handler: handler2 }]);
  router.add([{ path: "/", handler: handler3 }]);

  resultsMatch(router.recognize("/"), [
    { handler: handler1, params: { }, isDynamic: false },
    { handler: handler2, params: { }, isDynamic: false }
  ]);
});
```

the order that you add the segments in determines whether the test succeeds or fails, which is no good.

**Comment by nathanhammond** [comment]
This is addressed by maintaining specificity on two axes: segment score, and segment count. I've addressed it in [ember-route-recognizer](https://github.com/nathanhammond/ember-route-recognizer).

**Comment by nathanhammond** [comment]
Test ported upstream and passing. 😜

**Comment by jmeas** [comment]
Cool. I see you cover those two concepts in your blog post – can't wait to read it.

---

As an aside, I've always felt that the NFA approach taken by this lib was a bit heavy for what this lib does, so I'm surprised that it's stuck around in your rewrite. I could never find any substantial docs justifying using it over something more ad hoc but simpler, but I'm anxious to be convinced to change my mind by your post :)

**Comment by nathanhammond** [comment]
@jmeas My implementation is really just a radix trie but using a NFA-like transition function to walk it. `/*foo/:bar` is the only reason we must use the NFA approach. I tried to do a pure radix trie solution in #90 but ran into showstopping problems. The other options in this space (brzozowski derivatives, bunch of regular expressions) have perf hits that we can't have.

**Comment by nathanhammond** [comment]
Closing this as it would break our backwards compatibility story and the goals we have around specificity.
