### ISSUE TITLE
New decode rule doesn't play nicely with Router.js

### ISSUE THREAD

**Issue by nathanhammond** [tildeio/route-recognizer#96]
Router.js: https://github.com/tildeio/router.js/blob/master/lib/router/transition-intent/named-transition-intent.js#L176

Change to route-recognizer: https://github.com/tildeio/route-recognizer/commit/8f7845b7ac03d5ae4bb4b0a241458635e3b6d9ae#commitcomment-17798449

We've broken unspecified but used as public API with this change.

@bantic Do you have other thoughts on how you can do this?

**Comment by bantic** [comment]
Ooh... :/
Yes, I am pretty sure we can do this another way. One possibility is to maintain a separate array of `shouldDecode` booleans that matches up to the `names` array, and modify the handler to have a new `shouldDecode` prop.

I will take a stab at this.

**Comment by nathanhammond** [comment]
Closed by #97.
