### ISSUE TITLE
Hi, I'm a member of cdnjs team

### ISSUE THREAD

**Issue by x09326** [tildeio/route-recognizer#98]
Hi, I'm going to host this lib on [cdnjs](https://cdnjs.com).

But I meet a problem.
I downloaded this lib from npm.
I tried to minify the files in the dist folder.
But I failed. 
I try 3 minify tools but still cannot minify it.

Could you help me to minify it?
And if you finish it, please update to npm.
Because we prefer to use npm auto-update.

Thank for your help!
https://github.com/cdnjs/cdnjs/pull/8444

**Comment by rwjblue** [comment]
How are you minifying? What errors?

**Comment by nathanhammond** [comment]
@x09326 cdnjs isn't one of our target distribution methods. If you wish to implement this we suggest that you mirror the bower distribution. This is typically a foundational library which other (larger) tools consume. Thank you for your interest!
